### ISSUE TITLE
Decide on a web framework for public website

### ISSUE THREAD

**Issue by rhefner1** [cookomatic/cookomatic-web#4]
This repo will hold the API code, which will be hosted at [cookomatic.co](https://cookomatic.co). We need to choose both a Python framework and a front-end framework for the externally facing website.

This site will need to do the following:
- Be a landing page for people interested in the app (our ads would point to this). Someone could launch the webapp or be linked to the App Store/Google Play to get the app.
- Be a teaser for dishes on the app. For example, Googling an album returns [this page](https://itunes.apple.com/us/album/brand-new/id1023525896), which is a teaser of the real content that lives in iTunes. Users should have the ability to see view dishes on the web and have a deep link to them in the app.

## Python Frameworks
- **Flask**
  - This is current what is in the repo. It's conceptually simple and easy to use.
- **Django**
  - This is more fully featured, but more complexity. See [this issue](https://github.com/cookomatic/cookomatic-api/issues/3) for more details.

## Frontend Frameworks
- **Jekyll (GitHub Pages type framework)**
  - Write content in Markdown and site is automatically built without much effort at all
  - Trading flexibility for simplicity
- **Bootstrap**
  - We can get a theme for free or we can build out the site using the starter pages they provide
  - Well supported and easy to use
  - Would require building out each page with the framework
- **Others?**

**Comment by ceelias** [comment]
Decided on Flask
